elasticsearch:
  image: library/elasticsearch:1.6.0
  ports:
    - "9200:9200"
logstash:
  image: library/logstash:1.5.1
  volumes:
    - ".:/config-dir"
  command: 'logstash -f /config-dir/logstash.conf'
  ports:
    - "5000:5000"  
  links:
    - elasticsearch
kibana:
  image: library/kibana:4.1.0
  ports:
    - "5601:5601"
  links:
    - elasticsearch
